name: Deploy to Azure Container Apps via Terraform

on: workflow_dispatch

jobs:
  deploy:
    uses: ./.github/workflows/template.yml
    with:
      cloud_provider: azure
      tf_directory: terraform/azure
      tf_vars: >
        -var "image=kanji-flashcards:latest"
    secrets: inherit