name: Deploy to AWS ECS via Terraform

on: workflow_dispatch

jobs:
  deploy:
    uses: ./.github/workflows/template.yml
    with:
      cloud_provider: aws
      tf_directory: terraform/aws/app
      tf_vars: >
        -var "image_repo=ghcr.io/${{ github.repository_owner }}/kanji-flashcards"
        -var "image_tag=latest"
    secrets: inherit