name: Deploy to AWS ECS via Terraform

on: workflow_dispatch

permissions:
  contents: read
  packages: write

jobs:
  deploy-aws:
    uses: ./.github/workflows/template.yml
    with:
      cloud_provider: aws
      tf_directory: terraform/aws
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
