name: Deploy to Azure Container Apps via Terraform

on: workflow_dispatch

permissions:
  contents: read
  packages: write

jobs:
  deploy-azure:
    uses: ./.github/workflows/template.yml
    with:
      cloud_provider: azure
      tf_directory: terraform/azure
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}